import {
  Ticket,
  TicketCategory,
  TicketPriority,
  TicketStatus,
  FeatureRequest,
  ServiceStatus,
  AnalyticsData,
  NotificationPayload,
} from '../../types/support';

export const mockTickets: Ticket[] = [
  {
    id: '1',
    ticketId: 'TK-001',
    user: {
      id: 'user-1',
      name: 'John Doe',
      email: 'john.doe@company.com',
      phone: '+1-555-0101',
      organization: 'Acme Corporation',
    },
    title: 'Dashboard not loading properly',
    description:
      'The admin dashboard is taking too long to load and sometimes shows blank page. This affects my ability to monitor transactions.',
    category: TicketCategory.BUG,
    priority: TicketPriority.HIGH,
    status: TicketStatus.ASSIGNED,
    assignedTo: {
      id: 'admin-1',
      name: 'Alice Johnson',
      email: 'alice@support.team',
    },
    createdAt: '2024-06-01T10:30:00Z',
    updatedAt: '2024-06-02T14:20:00Z',
    attachments: [
      {
        id: 'att-1',
        fileName: 'dashboard-error.png',
        fileSize: 2457600,
        fileType: 'image/png',
        url: '/attachments/dashboard-error.png',
        uploadedAt: '2024-06-01T10:30:00Z',
      },
    ],
    messages: [
      {
        id: 'msg-1',
        ticketId: '1',
        sender: {
          id: 'user-1',
          name: 'John Doe',
          email: 'john.doe@company.com',
        },
        message: 'The dashboard loads very slowly during business hours',
        attachments: [],
        createdAt: '2024-06-01T10:30:00Z',
        isAdminReply: false,
      },
      {
        id: 'msg-2',
        ticketId: '1',
        sender: {
          id: 'admin-1',
          name: 'Alice Johnson',
          email: 'alice@support.team',
        },
        message: 'We have identified the issue. The dashboard query is loading too many records. We are optimizing the database indexes.',
        attachments: [],
        createdAt: '2024-06-01T14:20:00Z',
        isAdminReply: true,
      },
    ],
    systemInfo: {
      browser: 'Chrome',
      browserVersion: '125.0.0',
      deviceType: 'Desktop',
      operatingSystem: 'Windows 11',
      currentPageUrl: '/admin/dashboard',
      timestamp: '2024-06-01T10:30:00Z',
      screenResolution: '1920x1080',
    },
    adminNotes: 'Database optimization in progress. Expected fix within 24 hours.',
    estimatedResolutionTime: '24 hours',
  },
  {
    id: '2',
    ticketId: 'TK-002',
    user: {
      id: 'user-2',
      name: 'Sarah Chen',
      email: 'sarah.chen@enterprise.com',
      organization: 'Tech Solutions Inc',
    },
    title: 'Critical: Payment processing failed',
    description:
      'Multiple payments are failing with error code 503. This is affecting revenue. Immediate action needed.',
    category: TicketCategory.BILLING,
    priority: TicketPriority.CRITICAL,
    status: TicketStatus.IN_PROGRESS,
    assignedTo: {
      id: 'admin-2',
      name: 'Bob Smith',
      email: 'bob@support.team',
    },
    createdAt: '2024-06-05T09:15:00Z',
    updatedAt: '2024-06-05T11:45:00Z',
    attachments: [],
    messages: [],
    systemInfo: {
      browser: 'Firefox',
      browserVersion: '126.0',
      deviceType: 'Desktop',
      operatingSystem: 'macOS',
      currentPageUrl: '/admin/payments',
      timestamp: '2024-06-05T09:15:00Z',
    },
    adminNotes: 'CRITICAL: Payment gateway experiencing issues. Investigating with payment provider.',
  },
  {
    id: '3',
    ticketId: 'TK-003',
    user: {
      id: 'user-3',
      name: 'Mike Johnson',
      email: 'mike.j@company.com',
    },
    title: 'Feature Request: Dark mode for reports',
    description:
      'Would like to have a dark mode option for the reports section. This would reduce eye strain during late-night analysis.',
    category: TicketCategory.FEATURE,
    priority: TicketPriority.LOW,
    status: TicketStatus.OPEN,
    createdAt: '2024-06-03T16:45:00Z',
    updatedAt: '2024-06-03T16:45:00Z',
    attachments: [],
    messages: [],
    systemInfo: {
      browser: 'Safari',
      browserVersion: '17.5',
      deviceType: 'Desktop',
      operatingSystem: 'iOS',
      currentPageUrl: '/reports',
      timestamp: '2024-06-03T16:45:00Z',
    },
  },
  {
    id: '4',
    ticketId: 'TK-004',
    user: {
      id: 'user-4',
      name: 'Emily Davis',
      email: 'emily.d@company.com',
    },
    title: 'User authentication issue',
    description:
      'Some users are getting "Session expired" error even with recent login. Seems intermittent.',
    category: TicketCategory.SECURITY,
    priority: TicketPriority.HIGH,
    status: TicketStatus.RESOLVED,
    assignedTo: {
      id: 'admin-1',
      name: 'Alice Johnson',
      email: 'alice@support.team',
    },
    createdAt: '2024-05-28T13:20:00Z',
    updatedAt: '2024-06-01T09:10:00Z',
    resolvedAt: '2024-06-01T09:10:00Z',
    attachments: [],
    messages: [],
    systemInfo: {
      browser: 'Chrome',
      browserVersion: '125.0.0',
      deviceType: 'Mobile',
      operatingSystem: 'Android',
      currentPageUrl: '/login',
      timestamp: '2024-05-28T13:20:00Z',
    },
    resolutionNotes: 'Fixed session token expiration issue. Updated authentication middleware.',
  },
  {
    id: '5',
    ticketId: 'TK-005',
    user: {
      id: 'user-5',
      name: 'Robert Williams',
      email: 'robert.w@company.com',
    },
    title: 'API integration performance issue',
    description:
      'The third-party API integration is causing timeouts. Response time is above 5 seconds on average.',
    category: TicketCategory.INTEGRATION,
    priority: TicketPriority.MEDIUM,
    status: TicketStatus.WAITING_RESPONSE,
    assignedTo: {
      id: 'admin-2',
      name: 'Bob Smith',
      email: 'bob@support.team',
    },
    createdAt: '2024-06-04T10:00:00Z',
    updatedAt: '2024-06-04T15:30:00Z',
    attachments: [],
    messages: [],
    systemInfo: {
      browser: 'Chrome',
      browserVersion: '125.0.0',
      deviceType: 'Desktop',
      operatingSystem: 'Linux',
      currentPageUrl: '/integrations',
      timestamp: '2024-06-04T10:00:00Z',
    },
    adminNotes: 'Waiting for response from user regarding third-party API documentation.',
  },
];

export const mockFeatureRequests: FeatureRequest[] = [
  {
    id: 'fr-1',
    requestId: 'FR-001',
    requestedBy: {
      id: 'user-1',
      name: 'John Doe',
      email: 'john.doe@company.com',
    },
    title: 'Advanced reporting with custom filters',
    description:
      'Allow users to create custom reports with complex filtering options',
    benefit:
      'This would save users hours of manual data compilation and enable better business insights',
    votes: 24,
    status: 'Planned',
    createdAt: '2024-05-15T10:30:00Z',
    updatedAt: '2024-06-01T14:20:00Z',
  },
  {
    id: 'fr-2',
    requestId: 'FR-002',
    requestedBy: {
      id: 'user-2',
      name: 'Sarah Chen',
      email: 'sarah.chen@enterprise.com',
    },
    title: 'Mobile app for on-the-go access',
    description: 'Native mobile application for iOS and Android platforms',
    benefit: 'Field teams can access the system without being at a desktop',
    votes: 42,
    status: 'In Progress',
    createdAt: '2024-04-20T08:15:00Z',
    updatedAt: '2024-06-02T10:00:00Z',
  },
  {
    id: 'fr-3',
    requestId: 'FR-003',
    requestedBy: {
      id: 'user-3',
      name: 'Mike Johnson',
      email: 'mike.j@company.com',
    },
    title: 'Automated data export to Excel',
    description:
      'One-click export of any data table to Excel with formatting',
    benefit: 'Reduces manual export process and maintains data consistency',
    votes: 18,
    status: 'Approved',
    createdAt: '2024-05-22T14:45:00Z',
    updatedAt: '2024-06-03T09:30:00Z',
  },
];

export const mockServiceStatus: ServiceStatus[] = [
  {
    service: 'Server',
    status: 'Healthy',
    lastChecked: new Date(Date.now() - 5 * 60000).toISOString(),
    responseTime: 45,
    message: 'All systems operational',
  },
  {
    service: 'Database',
    status: 'Healthy',
    lastChecked: new Date(Date.now() - 5 * 60000).toISOString(),
    responseTime: 32,
    message: 'Database responding normally',
  },
  {
    service: 'Authentication',
    status: 'Healthy',
    lastChecked: new Date(Date.now() - 5 * 60000).toISOString(),
    responseTime: 28,
  },
  {
    service: 'Email Service',
    status: 'Warning',
    lastChecked: new Date(Date.now() - 5 * 60000).toISOString(),
    responseTime: 2100,
    message: 'Email delivery slightly delayed (2.1s average)',
  },
  {
    service: 'Storage Service',
    status: 'Healthy',
    lastChecked: new Date(Date.now() - 5 * 60000).toISOString(),
    responseTime: 156,
    message: '85% capacity utilized',
  },
];

export const mockAnalyticsData: AnalyticsData = {
  totalTickets: 324,
  openTickets: 28,
  resolvedTickets: 286,
  criticalTickets: 3,
  averageResolutionTime: 18.5,
  resolutionRate: 88.27,
  ticketsByCategory: [
    { category: TicketCategory.BUG, count: 145 },
    { category: TicketCategory.FEATURE, count: 52 },
    { category: TicketCategory.INTEGRATION, count: 38 },
    { category: TicketCategory.BILLING, count: 45 },
    { category: TicketCategory.ACCOUNT, count: 22 },
    { category: TicketCategory.PERFORMANCE, count: 15 },
    { category: TicketCategory.SECURITY, count: 5 },
    { category: TicketCategory.OTHER, count: 2 },
  ],
  ticketsByPriority: [
    { priority: TicketPriority.LOW, count: 120 },
    { priority: TicketPriority.MEDIUM, count: 145 },
    { priority: TicketPriority.HIGH, count: 52 },
    { priority: TicketPriority.CRITICAL, count: 7 },
  ],
  monthlyTrend: [
    { month: 'January', tickets: 45 },
    { month: 'February', tickets: 52 },
    { month: 'March', tickets: 48 },
    { month: 'April', tickets: 61 },
    { month: 'May', tickets: 73 },
    { month: 'June', tickets: 45 },
  ],
};

export const mockNotifications: NotificationPayload[] = [
  {
    id: 'notif-1',
    type: 'critical_ticket',
    title: 'Critical Issue Detected',
    message: 'Payment processing failed - Ticket TK-002',
    ticketId: '2',
    read: false,
    createdAt: new Date(Date.now() - 30 * 60000).toISOString(),
  },
  {
    id: 'notif-2',
    type: 'new_ticket',
    title: 'New Support Ticket',
    message: 'Dashboard not loading properly - Ticket TK-001',
    ticketId: '1',
    read: false,
    createdAt: new Date(Date.now() - 60 * 60000).toISOString(),
  },
  {
    id: 'notif-3',
    type: 'escalated_ticket',
    title: 'Ticket Escalated',
    message: 'API integration issue escalated to senior team',
    ticketId: '5',
    read: true,
    createdAt: new Date(Date.now() - 2 * 60 * 60000).toISOString(),
  },
];
