import { useState } from "react";
import "./reportsTable.css";

function ReportsTable({ reports, onDelete }) {
  const [searchTerm, setSearchTerm] = useState("");
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 10;

  const filteredReports = reports.filter((report) =>
    report.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    report.id.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const totalPages = Math.ceil(filteredReports.length / itemsPerPage);
  const paginatedReports = filteredReports.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage
  );

  const getStatusBadgeColor = (status) => {
    switch (status) {
      case "Generated":
        return "badge-generated";
      case "Pending":
        return "badge-pending";
      case "Failed":
        return "badge-failed";
      case "Archived":
        return "badge-archived";
      default:
        return "badge-pending";
    }
  };

  const formatDate = (dateString) => {
    if (!dateString) return "N/A";
    return new Date(dateString).toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  };

  return (
    <div className="reports-table-card">
      <div className="table-header">
        <h3 className="table-title">📄 Generated Reports</h3>
        <div className="search-box">
          <span className="search-icon">🔍</span>
          <input
            type="text"
            placeholder="Search reports..."
            value={searchTerm}
            onChange={(e) => {
              setSearchTerm(e.target.value);
              setCurrentPage(1);
            }}
            className="search-input"
          />
        </div>
      </div>

      <div className="table-responsive">
        <table className="reports-table">
          <thead>
            <tr>
              <th>Report ID</th>
              <th>Report Name</th>
              <th>Department</th>
              <th>Generated By</th>
              <th>Created Date</th>
              <th>Status</th>
              <th>Export Type</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {paginatedReports.length > 0 ? (
              paginatedReports.map((report) => (
                <tr key={report.id} className="table-row">
                  <td className="cell-id">#{report.id}</td>
                  <td className="cell-name">
                    <strong>{report.name}</strong>
                  </td>
                  <td className="cell-department">{report.department || "—"}</td>
                  <td className="cell-by">{report.generatedBy || "System"}</td>
                  <td className="cell-date">{formatDate(report.createdDate)}</td>
                  <td className="cell-status">
                    <span className={`badge ${getStatusBadgeColor(report.status)}`}>
                      {report.status}
                    </span>
                  </td>
                  <td className="cell-export">
                    <span className="export-type">{report.exportType || "PDF"}</span>
                  </td>
                  <td className="cell-actions">
                    <button className="action-btn view-btn" title="View">
                      👁️
                    </button>
                    <button className="action-btn download-btn" title="Download">
                      ⬇️
                    </button>
                    <button className="action-btn export-btn" title="Export">
                      📤
                    </button>
                    <button
                      className="action-btn delete-btn"
                      onClick={() => onDelete(report.id)}
                      title="Delete"
                    >
                      🗑️
                    </button>
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan="8" className="no-data">
                  No reports found
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {totalPages > 1 && (
        <div className="table-pagination">
          <button
            onClick={() => setCurrentPage((p) => Math.max(1, p - 1))}
            disabled={currentPage === 1}
            className="pagination-btn"
          >
            ← Previous
          </button>
          <span className="pagination-info">
            Page {currentPage} of {totalPages}
          </span>
          <button
            onClick={() => setCurrentPage((p) => Math.min(totalPages, p + 1))}
            disabled={currentPage === totalPages}
            className="pagination-btn"
          >
            Next →
          </button>
        </div>
      )}
    </div>
  );
}

export default ReportsTable;
